name: Matrix OS Test

on:
  push:
    branches:
      - main

jobs:
  test-on-matrix:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Print system info
        run: |
          echo "Running on ${{ matrix.os }}"
          uname -a || systeminfo
